### ISSUE TITLE
Gyroscope only enable when you hold L2

### ISSUE THREAD

**Issue by Mistawani** [TauAkiou/n64emu-SDL2GyroInjector#7]
Hi, it's not an issue but i dont know where to ask this.

It is possible to just activate gyroscope only when you "hold" L2 ?
Thx for this great plugin.

**Comment by TauAkiou** [comment]
i think i was supposed to add that, but I never got around to it.

i'll take a look - i haven't touched this project in awhile.

**Comment by TauAkiou** [comment]
i'm sorry it took me so long to get back to this, i'm likely going to implement a separate sensitivity option for Aim Mode, which will satisfy this issue.

you can achieve the same effect by setting the standard sensitivity to 0 and using the value you want for the Aim Mode sensitivity.

i will reply back in this issue when that feature is implemented.

**Comment by TauAkiou** [comment]
This feature will be implemented in the v0.4b prerelease.

This is actually part of a feature which allows the optional separation of aiming and standard sensitivities.

See https://github.com/TauAkiou/n64emu-SDL2GyroInjector/pull/8.

**Comment by Mistawani** [comment]
Thx for your time TauAkiou !

**Comment by TauAkiou** [comment]
Note that the current release is broken. I'm going to release a new, more proper version tonight.
