### ISSUE TITLE
Movement bug in Perfect Dark - Strafing right as Player 2 is broken

### ISSUE THREAD

**Issue by Jodeth** [TauAkiou/n64emu-SDL2GyroInjector#9]
At the beginning of a mission, Player 2's character automatically starts strafing right. Pausing and unpausing stops the character from strafing right. Player 2 can move in every direction except right. 

Neither controller has analog stick problems.
Both controllers are DualShock 4.
GoldenEye doesn't share the same movement bug.

**Comment by TauAkiou** [comment]
is this using the latest version, or a built version?

i'll look into this tomorrow, perhaps there's a regression in the perfect dark code that i missed.

**Comment by Jodeth** [comment]
The latest.

I should also add that, after controlling player 2 a little while, the forced strafing will return and go away over and over, as if the left stick has a mind of its own.

**Comment by TauAkiou** [comment]
seems to have been a problem with radial menu processing. do you mind testing this build?

[gyroinjector-radialmenu-fix.zip](https://github.com/TauAkiou/n64emu-SDL2GyroInjector/files/10538108/gyroinjector-radialmenu-fix.zip)

**Comment by Jodeth** [comment]
Sure. I'll test it as soon as I can. Thanks for attempting to fix the problem.

**Comment by Jodeth** [comment]
That was it. You fixed it! Thank you for replying and fixing the problem so quickly. I'll buy you something on Steam. $10 or less

**Comment by TauAkiou** [comment]
no need. i'll push the fix to github and publish a new build tomorrow.

**Comment by TauAkiou** [comment]
closed by #10
